### ISSUE TITLE
Make lock stealing explicit

### ISSUE THREAD

**Issue by turadg** [ejholmes/slashdeploy#49]
Currently `/deploy lock` steals the lock from someone, which may not be intended.

Requested behavior:
- if it's already locked, reply with a notice that the lock is already held
- if you need to steal a lock, use `/deploy lock!` (like the deploy bang)

If it worked that way, people could lock in any channel or with Slackbot and no one would need to watch the lock history to know whether they could lock or deploy.

**Comment by ejholmes** [comment]
The current behavior is intended, but the requested behavior would be a huge improvement. Great idea!
